### ISSUE TITLE
Error al cargar la pagina principal 

### ISSUE THREAD

**Issue by ArelyCariaga** [roberto2torres/SSRestaurant#10]
usuario: arely7881@hotmail.com
pass: 147258369

shim.min.js:1 Uncaught SyntaxError: Unexpected token <
Reflect.js:1 Uncaught SyntaxError: Unexpected token <
home:11 Resource interpreted as Stylesheet but transferred with MIME type text/html: "https://autoservice-158722.firebaseapp.com/node_modules/swiper/dist/css/swiper.css".
Chart.bundle.js:1 Uncaught SyntaxError: Unexpected token <
main.47583ab8be15ea39054b.bundle.js:1 en-US

**Comment by roberto2torres** [comment]
El error se debió a la forma en que se estaban referenciando los archivos JS, si se va a agregar un JS externo  en index.html se debe agregar en la sección de scripts en el archivo angular-cli o utilizar CDN. Para reflect y shim se agregaron en el archivo polyfills.ts por lo que no se debe referencias en index.html
