### ISSUE TITLE
Precio en Menú

### ISSUE THREAD

**Issue by ArelyCariaga** [roberto2torres/SSRestaurant#8]
El campo de precio aparece vacío en el menú, se asignó un precio de 99 al item "brava de arrachera"

**Comment by roberto2torres** [comment]
El problema es que no se habían dado de alta categorias para ese artículo, y tronaba la aplicación en el campo de categorías lo que hacía que no llegara hasta el campo de precio. Se modificó para que en caso de no existir categorías dadas de alta se le asigne un "blanco" y así evitar que la aplicación truene
